# pub keys
keys:
  users:
    - &cody_THEBATTLESHIP age18nrs3xvekux4qnw4n952dadvldxchxguxpwquktehtyrj9tfy3zsgpxaat
    - &cody_starcommand age1dd0fw5j8rzpjl3wg04zl775uy0v7ngrwh4e8uzvsk7rxsgv9gvssx72jve
   
  hosts: # nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
    - &THEBATTLESHIP age1aw6c95pvpe0slyeupr5apr3f3er7guy4n6ng0a3ypsnxaxuzydys075n94
    - &starcommand age1x8u57848fnn4l0xum3cvy8p699cjht9gdk75xfwann5qpjfx8d0qgpqw5h


creation_rules:
  #path should be relative to location of this file (.sops.yaml)
  - path_regex: secrets/shared\.yaml$
    key_groups:
      - age:
          - *cody_THEBATTLESHIP
          - *THEBATTLESHIP
          - *cody_starcommand
          - *starcommand
  - path_regex: secrets/THEBATTLESHIP\.yaml$
    key_groups:
      - age:
          - *cody_THEBATTLESHIP
          - *THEBATTLESHIP
  - path_regex: secrets/starcommand\.yaml$
    key_groups:
      - age:
          - *cody_THEBATTLESHIP
          - *THEBATTLESHIP
          - *cody_starcommand
          - *starcommand