apiVersion: v1
kind: Secret
metadata:
    name: argocd-oidc
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
stringData:
    client-secret: ENC[AES256_GCM,data:GkQVAJ/GXnsjqZyYV4v9RGImY1bhDvDhq+0Y3yiRtjJJOwsdjpWawJC7Lk3O88GDSLASzjVe+8mlA7zl1gMASQ==,iv:fSQecvMfc2CP7vOj71VensOdzNhtaL8eARXSpPmcGEg=,tag:dc8vhxgNsAXsRwNhzVXPow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmU0hoeHlPcjlsb1VDS1B4
            dnVhRGY2VmJqU1ZPM2ltM0RlSWNGYVplQmxnCklhOGxHRWV2WE1tcVAwaTNUeVhX
            UVRYNTJvZzFMY01KQU1jV085REpqREUKLS0tIG85bHd0b29kbGJvbS9PczR3bkdU
            TXZqOWJxelJWdkk1aC9VVkp2MUtGam8KYkZF2Ejglv9EIlTpsbZRMx5tJoHk52P6
            U1BhoISjIoplMfKFkgO1VobrNsKcS5UXOUTw12ydQTgkd7M+DWBySw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7zglp8h0s4zvpgzjkzgz265msl52ugha7en4k84ev68h8tz0pnsczx9hf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T22:52:36Z"
    mac: ENC[AES256_GCM,data:5OWgRbKFHW88NgbH2jxjLsNSQszHmM1TZ56VEbea5yPGYb4Dl/Ju0cnDrXElPK9b0UtxfhU08xrs9Evn5MdOzWUXPXLQSToc02YonNGKDN9vxCkaCO9b8JRQVDkqQ3pW+RV+8wL4CkaI/aCenmB6sXiNScJGZeyt9kf23L7DTs0=,iv:hpdJCVxtLqzxSK/3g8OHTIq3d7ANre2KNz7FRNtBcD0=,tag:yHZWLmfdJTJjJg3pvVuwXQ==,type:str]
    version: 3.13.1
