apiVersion: v1
kind: Secret
metadata:
    name: authelia-pg
    namespace: databases
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:uZp0p82B+las1zytHAIlw+KMMvRuz8yQJhlaZHf1a1kzfRZfYDDc2vAa8mVLDRxh7fJyRthwEhHh9+GBn1Cbwg==,iv:FhH7TRpEuvwvJWNllz2wT72YD23gzgXTDx+eXhSBJBk=,tag:Cwn1D+aIFRdyd5vJHwTw7w==,type:str]
    username: ENC[AES256_GCM,data:nnmCKWFbbKE=,iv:GwaKWAdHyMryKP20CEvGmHVdKOw6BisjKqwcofGNGOs=,tag:slYMHNTZDoVoJkA27HLMGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxL3EwWWpYU01HM2NSOEZ5
            cDBJY2pEbWJIbHE5M0s1Y1MzV2ZML0ZVVTBVCmN6d0c1ZXNrRFdmWHdhSFpkODlD
            QUVHK2JmRWwyeHVIR0pHdlB1R0ljRkkKLS0tIEpKZFlqa0NFNVlmN2tMZmtOcFYr
            UFdPdjdhdHkySTNsVDh5MzJMekJUdkUK88MxOE6ExUhAgs6rCfsZdYHbXR6QRRkn
            bG3l/FbeAdpruAeMZv8oIJRriQ8m1RycBKZFA/viyN/VNCmZIpmI/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7zglp8h0s4zvpgzjkzgz265msl52ugha7en4k84ev68h8tz0pnsczx9hf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T22:52:37Z"
    mac: ENC[AES256_GCM,data:oYuKMpL22fnyfPn+8ti+wwzJquTNeYRIA6jBivnCyiR5NUHlJ4/8oom5H5n2C5MECkrEjgzu6rYacfTJnSNXhr8SeWeYFlA2H9n6qWM201X0l4HlpIa53UbNP3vUyc39ihTPrH9NdCPzOuANuHbgCNK1T7j+RDoI0kQjVdDGd7g=,iv:QFRchzJ1ErubzvmUuvD/iv03nahA56IEwk0q8tl3BVE=,tag:bNYWw9mMnuPEHi9ZiEkAHg==,type:str]
    version: 3.13.1
