apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare
    namespace: external-dns
stringData:
    api-token: ENC[AES256_GCM,data:lyd4fTe1PjR4GevO9DszwrdvV4qZfSxb2VEygTnL7cSphBjXPxqCPQ==,iv:sMQs+7VEDkHRETTxm27x1bybXE8p/y+e30g2CwleVyI=,tag:NzfKxF6LZg1jsqvs3nQQzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdGpSaVlhQkdWRjNlczRT
            ZkFHMzBOaDNHQVNvNkd4dVB3bGVkeEg4OVZBCisrd2lxamlpQ0YzSjlCQU1hUjVo
            a3Q3NDFhNlkxSDlYL1RYcW1QV1RQWE0KLS0tIG1UaVNwL3dPdlpkUG9mZm1kTmlr
            S2Y5enlvUjhLak9rT01kUW00dlFwQTgKG3K/lhriCcWmOgb3nbI06Org7l47or7B
            yWXwLFZNi5Tj8pyRq//KqChLwlrbvdAU+L0qp9+D/JtGrtrcqjgDwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7zglp8h0s4zvpgzjkzgz265msl52ugha7en4k84ev68h8tz0pnsczx9hf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T22:52:37Z"
    mac: ENC[AES256_GCM,data:EA+AdtFVy+0fhWvAxPeypgOGjBYfQKO3hnRMVuEZ8954A/dehIINOXdsK/3zBjOrlN1+A6sSMEfXaKru9/EFBtgQx/Ml4vawhNzCgyRHg+DljIsLCXICQknHv/XVXk0Vok0iU/mdquzrJRvc8/vN+GAzfl7V5ejfdO8HT7/BoRo=,iv:5tkjs6Lms8ySAvoBX224UbIIflLtHlDah/JlFzduP3U=,tag:+URKw/wE2+GcBs0+7tb9dA==,type:str]
    version: 3.13.1
