apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db
    namespace: forgejo
stringData:
    password: ENC[AES256_GCM,data:ucyHWZxdOr3pcsBlPZXbOJIerSjcbU0HBQDF6iQm5tLyLffYPvIPlFD1zCmxOUry,iv:OY22zMt6DXVzY6mt3rXt5tPZMoFbE25XPmWNftOoSig=,tag:zoe8qXY9UTdAn/jBy7tnTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eDhJeUR5RkFSbzZjSGZz
            RHZzZk40YVR6ODJwWWZUQlZWa3M2cWtCbnlvCmZ0Q2FvN0VqZVFIN1dUVWtqQ2VH
            a3plSVIrVmxES2plWXcrVVJxL3d3amcKLS0tIEhqK3hhSDVLY0hBbnRFQm13bUp0
            TEp5WHIrbHBYNmdqc3U3S2tnQVRSK00K4lANdwvMRQR64vJ8O8smTkRN4cBvXkOJ
            xzvhDpDonneZ1fMGx7sX/0yIClpA9XWZRSsVx2wm6ibG4HG3m9vAtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7zglp8h0s4zvpgzjkzgz265msl52ugha7en4k84ev68h8tz0pnsczx9hf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T22:52:37Z"
    mac: ENC[AES256_GCM,data:ao1Cfxt9IvMGs2eK1WK319JN9kWgQF8wg1XDNqWgoj5NvlEbsG/8Ro4qdU4oNUukHMJhPDSzXcqVVmhfHn1tChdnUVPMMIjYKZ/hB9zeF8Yxen8/X5mhpXN4grB2zt72048VDdCkzAajn3o+1h8FncM3cRG432edPG6NtaeuGS8=,iv:ZiDzhZdqLAeLNAuwAoQcSWUJPwzP9lsIrpSh3IdWm0Q=,tag:4MJEOsMwha0JG7Faj3ll/Q==,type:str]
    version: 3.13.1
