apiVersion: v1
kind: Secret
metadata:
    name: forgejo-pg
    namespace: databases
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:MwDx1y9qJXWP8mbgdzC0xF4St3un3y1RrqWVam9zvCLhEAJ/xMR5ykvEQLmCtA0J,iv:y0qZZ2rP3qxMmjjE+SPBOTLe0YUgR8uZj8B45ZhFsJk=,tag:EFaSWT8EmhV9O1I+86R+Ig==,type:str]
    username: ENC[AES256_GCM,data:xYuVycEtyQ==,iv:EkpgrI6kTldnJLPKmHNihAZOgOhOgT0pNYomH6rcp0c=,tag:epDKJidRtyaE8c9TqQ1cnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaERHYWRsYjBQTjBwRS90
            QVd2eE11WGtPaHpNQzdjQVVZOWdadnNzZHljCnkzUDBVQUdEd3I5WFlDQVNxWTF2
            WkNQMDB6T2lEbEFEOHhUTU9LcDc0Sm8KLS0tIENBSlhyeXo2RnZuNTMvdHBCcFBD
            cjJlUlV4Z3dxb2FETTUzd1Y3MHp5Wm8K4cumLiTdFzRqltKZ3ZLnXiPP+LGKbfhE
            jA0l7WNof1AiDKykeRKjzfV6z+7+1K/fym1nMeEWAZZ0uhcUKkBFtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7zglp8h0s4zvpgzjkzgz265msl52ugha7en4k84ev68h8tz0pnsczx9hf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T22:52:37Z"
    mac: ENC[AES256_GCM,data:naUuy/gtmL6DKSTVO8JcQdl2k7H2bFFovJGofp9ukj89wrF1szpUQ9Y4kamSUdaphiLH/Iaf8DXOfjRvOCv+yJMnRoAK3/ODr85Uo9WAv+C6G5E4pHGVnnrpOGznbyPVHJGlJMZkw+TynO2+56X7wzT4HXMGRnbW+Y8W16kF/vc=,iv:68IBNG47lox6Aw9GLTO5G63rv4uwBhyYDYAMPyudctY=,tag:OzHVEBBdg8X8EaKjqIIHnA==,type:str]
    version: 3.13.1
