apiVersion: v1
kind: Secret
metadata:
    name: gluetun-creds
    namespace: selfhost
stringData:
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:DH6QhqDPe0fTXd7cb0CBY23oyqq+5DNy7s+uBQ00fUQ=,iv:yQ3iymGGdS1xgPK1bmsdHy//B8cI7fiRvAwAaEhnTGw=,tag:aIa+mJwfGJyM6h9cBmh4Xg==,type:str]
    OPENVPN_USER: ENC[AES256_GCM,data:+th/Mdv17hWphOEKip1Atw==,iv:PC/0g3wu2lV0xjjcAm3Aa9W+1doLcI8PwTQvFhFBbF4=,tag:fftL/jY71Inym815DV0RhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Yk5DU09OYU1wdUVTcDVQ
            MDFhTGM5ZlZuVnBMeVg2TVpWWnJYVmtOTXlZCjB0ZWJPN2ZCMHZQZHV2aFpsanFK
            ZitSMSszdnZEdVhaZnRaTUIxWXUvRFEKLS0tIFRmb1VKUjZoM05LY1V1aENtK2xt
            c2IydWFJdTB0UXVsTFBneDlJalM1b3MKxCKL3EqY5Spmk2/FBShh9d59jqp7fbpW
            k7RIhG05ecztlz7voevQILtnqot24QIy0+sGi4G/nicW8co8hqkp2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7zglp8h0s4zvpgzjkzgz265msl52ugha7en4k84ev68h8tz0pnsczx9hf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T22:52:37Z"
    mac: ENC[AES256_GCM,data:Ymd/o3KQnk1MG+duCRZBqDgpKtpKLhgoO65mbt5MN8uAsob375InK/qNBZVjAX0u80HE4oVf4GpmJYUZFNG3ziazg1mLauWR/SKsQWDNCqbz9l0HXLwPyZfbxped1ZnN3pOcZtsiC7Vm9v8Yl6NxjfNBWuZHnAXFh1KzKv2q/LM=,iv:OoRZGViF9cd/vNFRezqfmgSdFJxcn71mnxzCoU/gqrU=,tag:B0AwGl/PRUJwyE6nufZUlw==,type:str]
    version: 3.13.1
