apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: observability
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:f3WrudtVYPnN/3Mw88a3dlSJdF+2ySAUHFVo2mjZekFsEvSQJol1jDeyqTd41kdbqWl4YU8O4jLoNzOgehhiclECeseSmxcqXy3uLHPw58KZe2oz/GcQd+hawzDA94kwdOjgFlK2w3xSKIaIqU7B9Xuq5RGQNhGeTIIbgfaCDps=,iv:RrTrZmh4WraFSv9yPfUYHkSzQ9rf7/xqxQk3DQJ06bU=,tag:BVwLFzHRt8eBpymt1k8ezQ==,type:str]
    admin-password: ENC[AES256_GCM,data:CyDgER8WSUuKnTpI1eN2zD/+xTRhefxcp1PVXz44oczZG+LsN7aFzTLRROZ8ks98+NFXRbM2AzoUdiUPkU3s/A==,iv:iO7oDg6jVRs2XhPZZqRJXP2S01yS9dxn7e5dQl4ByDI=,tag:Ce6deQ0GSOtiMUAYw5ATkw==,type:str]
    admin-user: ENC[AES256_GCM,data:O6k0Mm8=,iv:dWVXCfc+ZqwyRVMQsEvpb18XQuT3PUSEJ6RMjfvxJNc=,tag:r/tL2aiecEyDdfJSyRAr7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveWtkVXVwdDE1OFNsRVNL
            dWpVN3dBTktKM1pIaHB2OGRkb2RURzkwMEZBCnVYQkhIZVFmU1dIRW5yZzJzWW5p
            ZFhnWnNCQTQyMGgxa1p5aS9TeGN5Yk0KLS0tIGlZR3A2dUFkN2pqeGR0YW1IL3lN
            TUFINWs4bWxkUStFNGtjelNVQ0xyY28KUuHfnsZKtn7Hu2LeyuMXTtkOjQ/WypGF
            hYSiXTYzl1zbVNAmedn07h9SdiTMHGo8NVqThMGtB93oVNrlo6sEhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7zglp8h0s4zvpgzjkzgz265msl52ugha7en4k84ev68h8tz0pnsczx9hf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T22:52:37Z"
    mac: ENC[AES256_GCM,data:VeOCcqXf4vRkXlMDI2HoFC9PIAWcxBZNfJ/v4DNBmVaJZdWqpt2UkGm5TAnJkJsJ73VJrFoDCD0DZ3zVKhV9t+C9BX2FHRVemwuzER/RlY7pj0FGtP66hARdSRegC3IEdga8ajoUdnJj87h5kDI0ixJZ6lTRIKBVEUxZp8yNTLw=,iv:1uvfYcxUaskYYSveFuNaQ44i+uhStPaWbyMVQIfA/wY=,tag:Q7a+M8WU4P7SQ7OYovrNcQ==,type:str]
    version: 3.13.1
