apiVersion: v1
kind: Secret
metadata:
    name: invoiceninja-secrets
    namespace: selfhost
stringData:
    APP_KEY: ENC[AES256_GCM,data:m3ued/TMppf8OGuRNgJCcaBmcBcJ03k9o3UjyCXVSeIRm/VQ2CpVBhsvN/A9EFBoBF05,iv:aShfR7RRL2O/SKt2t98rpSEGywytZcnlhfz8EycVR9M=,tag:CVlZK/5UytFX8Mc+2bap0w==,type:str]
    DB_PASSWORD1: ENC[AES256_GCM,data:JPwx+k6KBPp0MPfznBNJDGQKgbAUcCvOWOUCAC52O0jLKkkxaoQ/BbKJrtvTtWPTnoF3ekxOMhenGnFBYd2HSA==,iv:z5qlBJ6VYbPOPnKPmnn+WhF/VVZARDDDenVG+I0PEco=,tag:SNKpL+xrRXuclbGD9e64kA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSWFZT0J3VXp5dkI3R2sw
            QkMxNEtWeUhIV3IvVmUveGo2MHN6MjVsOEhzCnRETDRDVUFGK0doTW1xSlNyNXdo
            Nk1hN3l1RE1ZRERSeDJ2d3FCaHN2a28KLS0tIEd2T1ZmSDk5cEpHdlF3NG9aRTEz
            ZXlNOHMxaE50MUxxRXJRM3FzVElYM1kK/A346BsszGCKKGQCgcQ3AYATfkdvcL8A
            y2DMAMIrb2VZaAbgOaVdThSpK+cg2qcXryXtDqmcg3WEvSGthw4iYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7zglp8h0s4zvpgzjkzgz265msl52ugha7en4k84ev68h8tz0pnsczx9hf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T22:52:37Z"
    mac: ENC[AES256_GCM,data:uQwecDAm3vNkflSgWo+7S+aoZIHqQ7ML+1nzXY8DTUAKesdqW89VPSqg2vkYegRy22tT7iVLAmFKdUCFQ+ri7iJCU0msBp05kWX7WNdPnZKa2zwcv/DH1VXjzDT+LakDMi0E+JH2ftMLrUZBNSpL7FlffQwXqf/yVIKM2WHZhEk=,iv:/Jh2lhlo4NFGqX8U9zX1Us11uWOeyfDDQGjmpZlqC+o=,tag:xKl1cZihuYiEzuxkrOfNLQ==,type:str]
    version: 3.13.1
