apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secrets
    namespace: selfhost
stringData:
    meili-master-key: ENC[AES256_GCM,data:aFgWQYI0RoZYUtjumzTJZSDfpeh/zQM+GKa1V2bPepG9j64+swzlxT1Wr7Q=,iv:rN/d9dmMKZ4tSDWHJ1qksO4CI00gxiKgrN+UU+lc34c=,tag:Md++aPipXGffi8OtQooA8Q==,type:str]
    nextauth-secret: ENC[AES256_GCM,data:awHFbSAvLdLDD4wZtIuCxRfNNQTZSxdhbG6X+szo4jLuk6XCLL7aj8XJP3o=,iv:2TiILnokVYZtL/8EiQDMYImK/HbBv9270kkUKC4QbJ0=,tag:SEUknh6E454RdMALdfz3JA==,type:str]
    oauth-client-secret: ENC[AES256_GCM,data:W2V/7feGB+nuNsMcZqmnemXElaGnZt0ToGs2qgD4itt5SXl8khPUtIXwZRo=,iv:pjt4rS/aU69W4NCB1gfslTLpPGlsI6tNYWncLNwcuZA=,tag:8Oxh6spp47zYcv8OOPdSow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNFA4MzdPeGl2eWVjT1Uv
            Z0J6WW94Qmt0OXpUTDN2dzNCbVBCbmtZNmtFCjZxeG56Nzg1WlZmUS9tQ3JocFlk
            dnlxTXRrc3RZeG53SGpwTjlocVZJVHcKLS0tIGNjN0paVVBLSnhyVDlkWWZyMmtq
            R0J3SjZqZTZsUGdXbXIxSzJQV2J6cDgKbK7/yfe3YohGlJBfzJWLR498ABHIqr3h
            KdsTeBNhpYLjqT8Q2yK0CPPnoKJZlzvehsR3EIbYG+6fvUi7Waf5NQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7zglp8h0s4zvpgzjkzgz265msl52ugha7en4k84ev68h8tz0pnsczx9hf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T22:52:37Z"
    mac: ENC[AES256_GCM,data:IeEE27NLJNEPId54BVG1F+l8+ZgEWhhdwGQcQRzalI8GJt2ou9K7yWjhW9QlMeTqpyIizQzpuEo6bcS4WNv+tyiS/2ArsRtObNDJ12coucMhxAjwycv7IxXH9AQjq1MyIo3CfAv/OZPDCzDEwapxxKIID+LNgpU3ZBMsWSlkNhI=,iv:y+/wmRTbPH4DtcO1Ry4FI6eynWReTAGzamgV7HNTv1o=,tag:MTQf+iAMddH+6xfTK+axEw==,type:str]
    version: 3.13.1
