apiVersion: v1
kind: Secret
metadata:
    name: lldap-secrets
    namespace: auth
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:z9VZ9uwYq/1zYwVlB7LZ+lkchxa8UkjEoWtaTYkSpV9wPOgBsiwsh4lRPr0=,iv:lj5MA9nDcuaLxiukSBsSN+39bdlfymsMlp7BFEjdeNc=,tag:pm2t0DwkX5U0zkB5yrQNbQ==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:N5JcOsC83coZCYUaPP0vmIuGfsZanfmCPD/d/n6zUYH0eEoJlfHEWqXbK4c=,iv:dlFQt+czgd0xgunRYwwTFDcaOOcNQYFCt92xwZgW1hw=,tag:ooTwkOdmAOKYmcTYBWTm1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHd3VHM2hzbUJnVlBUYS9L
            QmxRNE9aSm16V0huMHlKYkZjS1JGaElCQ1g0CjhWek1YTmRMeFBIeUJXRXVlUjR4
            a2NvL3FBalpqQlNNajhQRGR2RGRWVEEKLS0tIEJXTVNrWW9obGk4b0h0OFBJOFE2
            OVd1SzVuSElKQ2gvRDgvN3ZOYXo4QlUK+NMXb5XfeCk/gkDcFpe4L/NiDn0P8z4N
            54UnVaOE4PKjwLWqJ252/JamyxMGeh569e6gjVeVRc1u03AzpN51HQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7zglp8h0s4zvpgzjkzgz265msl52ugha7en4k84ev68h8tz0pnsczx9hf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T22:52:36Z"
    mac: ENC[AES256_GCM,data:39XAfp694vZwSAPbRUyKLixWxqrcRj6p+z6bq9OA0ZCTP9tO2chFP4P2sZxfs78/ea6jT7UT58T7eojIcQv7KWAyU2kIx12CpKLZ4V1UM35aTdkUUGMknCFhdbMitRByd+m6z0UZzNlXIjVWQMFwNbg8KLtOIhtaoJZjQn80kpQ=,iv:OYfe0XDCEa546PW1KWE3ut9rt1h4OWb/mN0q1eZUCWA=,tag:VJApnOW90ArJ2SavR0scPw==,type:str]
    version: 3.13.1
