apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-config
    namespace: nextcloud
stringData:
    config.php: ENC[AES256_GCM,data:GgVCGQwbjRAVZio5mDwuHAoWtNFTD06NV2BJBdWTk4Y6/OzP3xyZt7MLm1SCBKwZO5CzYQK5a4Zrt5tC3qY2ZUIAbpvK834s/tGfRAGTuWdPH5hwTJ4hbie5+gJHlww5YK4tLcQkL6u2WoAAgmfx2FOzbBbPHkvxcP+kBLQaQvD+dQe8CQeImrxVWNruw9PmUEOmCIS0MauSqhu8XCi33BQFauQFwV+cTOaXcQdcrb6VPvlsslbbY84VvW6zkGyM1P6ZmjLd8bKLaddZgNka/60UxmjaYZ+1sEZ/0j3bYoNTuxc+pj0KwIcoKq0B6ojWCxKDQDHpyqlaLQb82Uvs8hXkedILmk0iiq0TQRRS+FpdUxZjl9gxzedxEvnLrCSedZFu+uMaVkfkDY+s+/vvAzGgAtXFOZ1a+3mJ4ZFkh9zgjk0U+kIrfvqUAwHeykaUt876uAtDhbAgSsbMM2EJqMWGQ62fGKtCopcsux6bscQ7sLZNnTd8qXz2bSQwyuIZB4Anu1byrgn80eem+tS9Mqy47sxu/RJO4ep2Z7VeZXhaC6aA8T4LWWYLBCuXLZl9c1Jk6xzymkUOcfuk4c65icHYP4DCn5yPZ+lSmSzG9kfbAJlDreXFKXlaZPBMkQCtb0HAXFV3hCnNTL3oPqaAQyak6H4HQoIJyMvPajr7D7TQLx2eruSo4xyYe8j2T79N29pOSmLwbi69lmVnS3O9oi7RWVNce9GQd74IiRTWwdsWuOyULpFGHYFOAYdZYIEn3K04try52XgggB33iE4ekDeKQ47oI9Hbwwbk4gQw3yGHMWqr8Lns9s39j0Noa98g6lRGZ6syhgVWHcAZhCjyYnjG0cK3DtGNspgjZFjLv7LD2jcdoLKT255UQDub7mcQg8fUeTm5y65sShGpAhML/w7QHWfeXdQoNFOomSSFxK0zIT8cbcn2FSLTCW+1mmWvBS7FZU1wK2U0pT8mWUKIfIAu2MaiZR08IIFMV9yk/K0kcb+SAoabmlve4DhKyYH6dC6tmfcCgsq44DweRD0Lq+CKLx4igKIA9aHCviB/1nLDUVlHNR6XPJ8dPFmSWC+/VwZGQixhPLKo65fs8QS2OkKx9dI78IX1fAgC+j+ZQ5AicUT+YLA4L3Wfgx1w35UZbeQzGSqZlOmz6Fcs8esV4MPiRrXEBN+UUtUErZWfeb74O2f8nLLFHA7uoB/wTJZR+VEg6E3OySw4ZxuJbjkTm3JVKc+xfZRddaoJkVBsH8RCievlmMx2Te1j0MJ16yqbgRxy5maP/iB0W0pR6WFxbqzt1vZp8dzqx0nWXS517q8bP45Vj7L9AxGvQM2J/VrDPBlqyU6yS+fcQydX1GA8x74E0mqX+dSdGKYxsGhkumfKMAIQ4+zmk03Q,iv:J0xkdUScrWS7ZSTq7Y7mQ1uwQ0SBpWEXN1gO9vGEfxE=,tag:l+DIo6jDn4fP5DnhtBf/sg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibDRZRGlkSmlHRXJHK0xG
            ZEt1ck5ka1B5N0gxZkVtczVMZjcwRkZScG1ZCitPTTlWcnNhN0FESU1EeDhUdll3
            ajMvS3l5VVJZTGJ2RVZIakFpdllkbXMKLS0tIFVPOHhlaVN3bFRJMDd0LzRpTnc4
            VHZabGYvYmRpQlZiYlZyb3l0bjN5a3cKCQtRb+MZ+nkrdtx+dl8oyjf7f26LD+gx
            TBUNEgPkFVrQYLoGCVXd2ESH3cc8N4HLv+y9eIOsj+cVYOCZXmXE/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7zglp8h0s4zvpgzjkzgz265msl52ugha7en4k84ev68h8tz0pnsczx9hf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T22:52:37Z"
    mac: ENC[AES256_GCM,data:LMBYtdAy+HZOmBtVCP94X4QA+E5XDhvj2cWq6/r8VI7OrXap9afg/DiNNllMWure+Y7TbbdFIhkGdsO1GOScEPERJMUi6MNp1Lex6H1jHZLhhEjefzDoNznIleVGR6mVI3KvfrRV4/e855/AaKDFWI16LXpD+OVNZJfnV7yCbG0=,iv:glJAFiXzbG1TQLIhs+xB+GH32IjI7zPKr+7qwizyMXw=,tag:w5TZtio2Nt9ksAEIuq23UA==,type:str]
    version: 3.13.1
