apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-pg
    namespace: databases
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:MwuTW6rw8cgR77L37rRWslV82m3AxrwZMAhh1D8n63eYcHp8DXjDE1rp23e9jO3g,iv:BD8C8sU90MQ/Ihn+JGD1zj7P/UZ02nO77GjBZrw8J1g=,tag:wHhZDavjqq+YHQecVHBukQ==,type:str]
    username: ENC[AES256_GCM,data:WjF93yMeonUe,iv:O5anuSzp7+oVIk1md+O36injN6/PSeb25AHZNI4Pks8=,tag:4TCm5uXeh4tZXSclRxnXFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxK2U0ejY1ZjFNMmVPOW9o
            NjNoYzB6M2t4bFhVb1hGYzBGQTZ2RkZpS0RVCjlhTWk5SzdtRDlqYVRGV1kzQ214
            TTMxUjVTaTBxL0NDY1RWZWxhY3JrKzQKLS0tIDJYZUtZUzJwM2hHQ044NllhMk9h
            ZTM5alZSR1NNZ2RoYzVaclg4WU9BaEUKpiKBMWxH/ML04PdL0cSpLK0+ulemkF77
            ptgKXsQlPvEXzhG6m9shFSeKfgsG21Aw+gOnjVPLi2rHmMjp6fgYSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7zglp8h0s4zvpgzjkzgz265msl52ugha7en4k84ev68h8tz0pnsczx9hf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T22:52:37Z"
    mac: ENC[AES256_GCM,data:GhLLfWr9uGXCeOyHZs2OMwmxRmf/dddLj/Dl8trFhfxAhN/U2qcuEUZ850gg0TCQpiTPIdl6XmycSBXoXb54OkflQ6aJWJEhM7iB9MXs92Ancuc3RobZ+NORdpKpi3aUcW4ggNPwOo3GCUJu5Byt0CoZGqatcz5iP/s1GMKYnfs=,iv:QhzQIx/DrJtWC1N6pdpAB2u2d6DapprphVohN7EBEAY=,tag:9O1z828qEAgBX0Ofjexvkw==,type:str]
    version: 3.13.1
