apiVersion: v1
kind: Secret
metadata:
    name: open-webui-oauth
    namespace: ai
stringData:
    client-secret: ENC[AES256_GCM,data:VcmsJxi8FzoUHVUenNOr5OcJTnvbmGdHoAvbuK2sUVr4ZQIrnatoS4psRQfd3te79E2ns8100W7IHIcyeKRh5Z/rF81eZJsA,iv:3kJiWpYb8cnm6G1LGaOg+XbEViXTylsoMMJrBJgnZko=,tag:s/0rdORkxnBOTLc6TBqiYQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QUFTT1RnSlkybmQ2cW10
            NHNPVnNac2VVc2ZVU2tMMkRpVmptb3J6UGdjClhjSlZvZm5tVjYyWVM0OHQ5YTk0
            R2dNaTYvR1Ywd1RrWDBYanNERmwyMW8KLS0tIHcxKzBPalBORmZnYlZxYTFnc3Jv
            YjBFNkZvNjAyL1dXYTFWMjRmZFFla2sKVpp/RZ+U/WyjAQ+/i+uvTbB+tig023fH
            AFgd1QJyPmTrC7ebj1EkYfNVaJc7uN9+11MG8n7h5Fb8N6zreX43ZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7zglp8h0s4zvpgzjkzgz265msl52ugha7en4k84ev68h8tz0pnsczx9hf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T22:52:37Z"
    mac: ENC[AES256_GCM,data:xwhhqPuRr14WdR6SQZVnJuyFJ7UwsSvSb2vry0dMbjctJx+2iDSidT0jW/NCti2oOF6KC10YfJFiYZZkU08tVlmS2K1wnxTzRsdWoxJoWRNYxH9V1e7NcnUImoh7WQKsntTc3EUM/SqA+nzjev+hCuu0snKhvBYZLaDv5JwHjVI=,iv:JR/gZBMYeCJiaesYtFxWETHOXPsMSppngUJq6fIXJps=,tag:Kmsw1DptrzgxH3Pc/FV1wQ==,type:str]
    version: 3.13.1
