apiVersion: v1
kind: Secret
metadata:
    name: pinchflat-secrets
    namespace: selfhost
stringData:
    secret-key-base: ENC[AES256_GCM,data:8e1PRadEVloyUYef6cV1v0ydr039BXJNfmCwc6L4kDAZnDo33miQOfYpBBppqy2SbCGGppf65iUAqg0AukSlxAsQdrTsjfcRjiN51ps0/aE8RESsxuYIrQ==,iv:tPDI6SomVaN0oxc63jXnd5XNwvqq0LTBK1Q5Bt61oOM=,tag:RZHXzqcLRHOQuC9M2iKy9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaFFCNTdDcm0xYzhpZzZi
            dWQvbkk4N2ZqamJZVEY5cGpCWnlvQmN5cWpJClBDbVZTRkIzb1JpS2lkbGV5cWV1
            WmZiNjlxeGFXR2gxa0pOYThYTkNXeUkKLS0tIDRBRVV2OHZMTjV6dlNEdks3NnlX
            OVRCWmJuaEFpOWlRZTVkS0FERENZSHcKDWOtKViAuuUQQn7Y3jsPtdnHpC/bW28m
            yo9EDwHM549GCnsWniZ6VJJXMa3mn3LqmgYoZpG0BoelwrvaHgEZJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7zglp8h0s4zvpgzjkzgz265msl52ugha7en4k84ev68h8tz0pnsczx9hf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T22:52:37Z"
    mac: ENC[AES256_GCM,data:uQQXDY2f+KaHSZs22/1uPTBqqydViaAokTHYAXaUYXrUl3SoRUyXG//FFz/kroIQ7LPQGnt9Q07HBUpqb+aSawRLcL2mgHu9Dy9jyKr8I/nmtlb4Bzv0u00HBQJzXtq/FVafJd16HrLUyjE1Ug6QxqgpjkHoDCvwPfpd2ilAtJ4=,iv:N6MOGfgRaS1mqOEqCFSw5FXknGrHzG/GHyFKJXypASo=,tag:PlL5hVJPzw1EZWRdgfkxjg==,type:str]
    version: 3.13.1
