apiVersion: v1
kind: Secret
metadata:
    name: pinchflat-secrets
    namespace: selfhost
stringData:
    secret-key-base: ENC[AES256_GCM,data:GkgvEIke+2da3GYeF9Gv54wOPtmQZYFG8zh4h/KDuYtu+nL5AUnoi7V1l/OUjTbs7lFN35T42neD0Q1KGeWs6bFxtn1AcQrAu03XtkUdIyfu4deUh+vNSg==,iv:pY3ytHJpvjChpYBD8l00BkDigW+sPs+pWnKbzXV0lCM=,tag:CMfmrYbjWq+ijQ4dyNFY/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjV3l4YUN4SEp2azBlSWZa
            bkcwbUpKVWxIc0Y5b3hXUnBZUmswdEtxZTEwCld5VmtvWkJwRG1WeDJOK0QrUWcz
            RmhNVDZmRHhkeW5mdHhIM1JTdCtxeHMKLS0tIG9HMFZ4akZqRDd5OFNVR1JpbnVk
            d2RLUVZsV1FCb3FYbzVGR3NCN0Foa2cKk8BNBJn/jkgmRCGrWD0K5/jP83UEND6l
            uM/UJjLVJK6LtpbWL0pEDEyjiRR1K/yntIxvIsDPx7QQ/e9s3ukXYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7zglp8h0s4zvpgzjkzgz265msl52ugha7en4k84ev68h8tz0pnsczx9hf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T22:35:52Z"
    mac: ENC[AES256_GCM,data:Wev5i1dPuPMznFqzO62aqcfBVYKKV34yAqWTif697KcnQt/eIubOtRZLA+wgU+t+hhgZ+QsaW+BKdVqNUZMeP2t3l0XQyOHJFINRNfvenOcYZZWGs3NLyFlEJWDraigzqZJfoyvSahl0e6zGUAJ6bQf+5xTBqjnzOeJugn1IgLU=,iv:ln4RMb9K2UnvFocDM/l0Y5xAMWey8KsdH6xZbpefhgI=,tag:tZjLLbTMatjIN5CIOPfOLA==,type:str]
    version: 3.13.1
