apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-pg
    namespace: databases
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:zDno5ZS24npkve8y3nXZeDnHq1vqt3wuQp9JVzG7pFGyD2OhyU9my4J7LYpPD3ki,iv:To9mS+b2O/h2xB89Ce4lhvBRZT/6b9k4qIBelg8KRmA=,tag:oNRpPy84nG4ZaubspjoNiw==,type:str]
    username: ENC[AES256_GCM,data:KpelzANVT+t00sU=,iv:JnVc7BFCG64wRUaZ/Fk5r5qkP5eJqRof8zqeg0I5dfo=,tag:n0jnuvOILypIuhPiX3ZAmA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL0tucWNkMnkxV2h6QW5D
            OVFJWjMwMW0vWnJ0M1JnTEZ5M2EwT2xsb3c4CkxBZmw4MFlIdVBLUWt5alRTcVNE
            NUpnME9zWTc0TVFzaG1hYnVZbGNWQnMKLS0tIDViU0tlR0NHU296aXByWUM5Q2lx
            T3Y2VGJkNjFxb0w5TkwxRHdtYzZ4VnMKT6KeB0vt7AmaaWgl+udJGy3A/Z3PWOTY
            eA35HSUPM+EzORA8DX+LyQE0u9GF2xxaT9u32jPsjySGguHYvHOoZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7zglp8h0s4zvpgzjkzgz265msl52ugha7en4k84ev68h8tz0pnsczx9hf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T22:52:37Z"
    mac: ENC[AES256_GCM,data:VpxpytHttuKR1XpHSoEykybbPn0jmK8J8hxfEN0VD4cBlL+aKs9jdYVxv8Uxtw5d5biozt/1cP4ixha4B8clnqEsOkqnvUdcbrkDHspdfPH6WH3X7g5Z2ywF0ms+UMipn1VVSzt8RQpmRat9piMCyKCuDtCbRXwjPc2+N0fAZak=,iv:5X6QmkCnyMkGfjtU5MeVIoCVmzI7UrdGRXAZYjfIFro=,tag:6HmWGIAHjZ8WPFfn8dPVDQ==,type:str]
    version: 3.13.1
