apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: selfhost
stringData:
    database-url: ENC[AES256_GCM,data:PKkWyJqBOBUbvCpeWTl/YbjQF3Tg5FFse/ExDOJJDeKkk/IzhZ4gNs0AjKBhsi5un5jp8zjTHD6SDKoXs3YEi0tGy5+lRHl25pcFxqHCfEJPZfaLxtQKvy5rRhf4CEkNaqEVHsVKJjY/EwNlngzAnZWssw==,iv:FMBYlMgCReTCqztI9g+97KcgF8zLhTaaB/TtKnX/618=,tag:Bx0sR1uAsLa4NQdPhG0GvQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYndoOHRueHQxNWpMTUhN
            eS9BSHF3OEI1amp6TW9JSGJlNTB1SzVYaFdnCjNMTVEyUDg0VEpUQW5ZNUZGb1c1
            WWZLTEFaYXlkMXA2d2drK2JKVVdZNVEKLS0tIGVhbnpmVG5GMmNqZTY1eWFBQkJV
            bnd6RTNUNTk0alNuU1RrdnhiSW8rVjQKxVCC85GsZK/9ceQL4OdjE2itR03VadHq
            dNleDmYgQq1gDM30FjOTiDt+MoeWi7nV3RoZtDU49o4SFny/OjkV1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l7zglp8h0s4zvpgzjkzgz265msl52ugha7en4k84ev68h8tz0pnsczx9hf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T22:52:37Z"
    mac: ENC[AES256_GCM,data:Bl+63RymeWSiPbyYir5C+lbf4PDBFzFkEO1iPFumDOvcvRD9DS6TdI/xWAgbjy5haAr5F1adsvkZ0XiGtzseUVcgZ1X5TAEkcpG0MLGxheBaIr7R6MuqE+/CG+NGsDm1gg4WYStOGVZLEF7GLy8CCs7Qp76D9znwOcTXL67cCpg=,iv:6PClnJsVKdZsw4XJhWdjj6+5jYlH1caY23tlyiWSt8s=,tag:O/geqahl6nM3m7U0ZcjDCQ==,type:str]
    version: 3.13.1
