# Zellij terminal multiplexer aspect
{
  FTS, ... }:
{
  FTS.coding._.terminals._.zellij = {
    description = "Zellij terminal multiplexer with custom configuration";

    # Darwin-specific configuration
    darwin = { config, pkgs, lib, ... }: {
      # Darwin system-level configurations
      # Note: pbcopy is a macOS system utility, available by default
      # No additional system packages needed for clipboard integration on macOS
      environment.systemPackages = with pkgs; [
        # zellij is installed via home-manager, but can be added here if needed
      ];
    };

    # NixOS-specific configuration
    nixos = { config, pkgs, lib, ... }: {
      # Linux-specific clipboard utilities for zellij
      environment.systemPackages = with pkgs; [
        wl-clipboard # Wayland
        xclip # X11
      ];
    };

    # Home Manager configuration (works on both Darwin and Linux)
    homeManager = { config, pkgs, lib, ... }: let
      # Clipboard command based on platform
      copyCommand = if pkgs.stdenv.hostPlatform.isLinux then
        "wl-copy"
      else if pkgs.stdenv.hostPlatform.isDarwin then
        "pbcopy"
      else
        "";
    in {
      # Zellij configuration file (KDL format)
      xdg.configFile."zellij/config.kdl".text = ''
        // Zellij configuration
        // Generated by nix-config

        // UI configuration
        pane_frames false
        simplified_ui false
        copy_on_select true
        on_force_close "detach"
        show_startup_tips false
        support_kitty_keyboard_protocol true

        // Default shell
        default_shell "${pkgs.fish}/bin/fish"

        // Layout and theme directories
        layout_dir "${config.home.homeDirectory}/.config/zellij/layouts"
        theme_dir "${config.home.homeDirectory}/.config/zellij/themes"

        // Scrollback and session settings
        scrollback_lines_to_serialize 10000
        session_serialization true

        // Clipboard integration
        copy_command "${copyCommand}"

        // UI pane frames
        ui {
          pane_frames {
            rounded_corners true
            hide_session_name true
          }
        }

        // Keybindings
        // Zellij uses different modes: locked (normal), pane, tab, resize, scroll, enter, session, move, search, tmux
        // Default keybindings are reasonable, but can be customized here if needed
      '';

      # Zellij package
      home.packages = with pkgs; [
        zellij
      ];

      # Zsh integration for zellij
      programs.zsh.initExtra = ''
        # Zellij auto-attach and auto-exit
        export ZELLIJ_AUTO_ATTACH=true
        export ZELLIJ_AUTO_EXIT=true
      '';

      # Shell aliases for zellij
      programs.zsh.shellAliases = {
        "za" = "zellij attach";
        "zl" = "zellij list-sessions";
        "zn" = "zellij new-session";
        "zk" = "zellij kill-session";
        "zr" = "zellij run";
      };
    };
  };
}

