# Inferno - unofficial Dante implementation
# PipeWire-native ALSA virtual soundcard for THEBATTLESHIP.
{ fleet, ... }:
{
  fleet.music._.production._.inferno = {
    description = "Inferno Dante tools and ALSA virtual soundcard for Linux audio workflows";

    nixos =
      { pkgs, ... }:
      let
        infernoPkg = pkgs.callPackage ../../../packages/inferno/inferno.nix { };
      in
      {
        environment.systemPackages = [ infernoPkg ];
        environment.pathsToLink = [ "/lib/alsa-lib" ];
        environment.sessionVariables = {
          ALSA_PLUGIN_DIR = "/run/current-system/sw/lib/alsa-lib";
        };
      };

    homeManager =
      {
        config,
        lib,
        pkgs,
        ...
      }:
      let
        infernoPkg = pkgs.callPackage ../../../packages/inferno/inferno.nix { };
      in
      lib.mkIf (config.home.username == "cody") {
        # Allow PipeWire (launched by systemd) to call clock_adjtime for PTP.
        home.file.".config/systemd/user/pipewire.service.d/override.conf".text = ''
          [Service]
          SystemCallFilter=@clock
        '';

        # PipeWire-managed Inferno sink (playback / Dante TX)
        systemd.user.services.inferno-pipewire-sink = {
          Unit = {
            Description = "Inferno Dante sink node for PipeWire";
            After = [ "pipewire.service" ];
            Requires = [ "pipewire.service" ];
          };
          Service = {
            Type = "oneshot";
            RemainAfterExit = true;
            Environment = [
              "ALSA_PLUGIN_DIR=/run/current-system/sw/lib/alsa-lib"
              "ALSA_CONFIG_PATH=/home/cody/.asoundrc"
              "XDG_RUNTIME_DIR=/run/user/1000"
            ];
            ExecStart = "${infernoPkg}/bin/inferno-start-pipewire-sink";
          };
          Install = {
            WantedBy = [ "default.target" ];
          };
        };

        # PipeWire-managed Inferno source (capture / Dante RX)
        systemd.user.services.inferno-pipewire-source = {
          Unit = {
            Description = "Inferno Dante source node for PipeWire";
            After = [
              "pipewire.service"
              "inferno-pipewire-sink.service"
            ];
            Requires = [ "pipewire.service" ];
          };
          Service = {
            Type = "oneshot";
            RemainAfterExit = true;
            Environment = [
              "ALSA_PLUGIN_DIR=/run/current-system/sw/lib/alsa-lib"
              "ALSA_CONFIG_PATH=/home/cody/.asoundrc"
              "XDG_RUNTIME_DIR=/run/user/1000"
            ];
            ExecStart = "${infernoPkg}/bin/inferno-start-pipewire-source";
          };
          Install = {
            WantedBy = [ "default.target" ];
          };
        };

        home.file.".asoundrs".text = ''
          plc!default { type null }
          ctl!default { type null }

          # Generated by nix-config for Inferno/Dante on THEBATTLESHIP.
          # PipeWire opens this device once and exposes both capture and playback.
          pcm.THEBATTLESHIP {
            type inferno
            NAME "THEBATTLESHIP"
            DEVICE_ID "00000A0A0A0A0001"
            BIND_IP "10.10.10.10"
            CLOCK_PATH "/dev/ptp0"
            PROCESS_ID "1"
            ALT_PORT "4400"
            SAMPLE_RATE "48000"
            RX_CHANNELS "2"
            TX_CHANNELS "2"
            RX_LATENCY_NS "10000000"
            TX_LATENCY_NS "10000000"

            hint {
              show on
              description "THEBATTLESHIP Inferno virtual device"
            }
          }
        '';
      };
  };
}
