# Inferno - unofficial Dante implementation
# Installs inferno2pipe, ALSA PCM plugin, PipeWire override, and a Cody-focused ALSA config
{ fleet, ... }:
{
  fleet.music._.production._.inferno = {
    description = "Inferno Dante tools and ALSA virtual soundcard for Linux audio workflows";

    nixos =
      { pkgs, ... }:
      let
        infernoPkg = pkgs.callPackage ../../../packages/inferno/inferno.nix { };
      in
      {
        environment.systemPackages = [ infernoPkg ];
        environment.pathsToLink = [ "/lib/alsa-lib" ];
      };

    homeManager =
      { config, lib, ... }:
      lib.mkIf (config.home.username == "cody") {
        xdg.configFile."systemd/user/pipewire.service.d/override.conf".text = ''
          [Service]
          SystemCallFilter=@clock
        '';

        home.file.".asoundrc".text = ''
          pcm.!default { type null }
          ctl.!default { type null }

          # Generated by nix-config for Inferno/Dante on THEBATTLESHIP.
          # Assumptions:
          # - Dante/PTP traffic is on enp12s0 (10.10.10.10)
          # - this 10G Dante link does not expose a PHC, so Inferno uses the
          #   software/virtual clock path rather than CLOCK_PATH=/dev/ptp0
          # Adjust BIND_IP or channel counts here if your setup changes.

          pcm.inferno-dante {
            type inferno
            NAME "THEBATTLESHIP"
            BIND_IP "10.10.10.10"
            SAMPLE_RATE "48000"
            RX_CHANNELS "2"
            TX_CHANNELS "2"
            RX_LATENCY_NS "1000000"
            TX_LATENCY_NS "1000000"

            hint {
              show on
              description "Inferno Dante virtual device"
            }
          }
        '';
      };
  };
}
