# SOPS configuration for nix-config
# Generated on 2025-08-20

# Public keys
keys:
  users:
    - &cody age1vp32nrnmrj2cqs4jf2vq0c48ledfuqyzs99uc4hc5yxtvut8g95shl2z35
  hosts:
    - &THEBATTLESHIP age1aw6c95pvpe0slyeupr5apr3f3er7guy4n6ng0a3ypsnxaxuzydys075n94
    - &starcommand age1x8u57848fnn4l0xum3cvy8p699cjht9gdk75xfwann5qpjfx8d0qgpqw5h

# Creation rules for different secret files
creation_rules:
  # Shared secrets accessible by all users and hosts
  - path_regex: shared\.yaml$
    key_groups:
      - age:
          - *cody
          - *THEBATTLESHIP
          - *starcommand

  # Host-specific secrets for THEBATTLESHIP
  - path_regex: THEBATTLESHIP\.yaml$
    key_groups:
      - age:
          - *THEBATTLESHIP
          - *cody

  # Host-specific secrets for starcommand
  - path_regex: starcommand\.yaml$
    key_groups:
      - age:
          - *starcommand
          - *cody


