# SOPS configuration for nix-config
# Generated on 2025-08-20

# Public keys
keys:
  users:
    - &cody age19exncpv8s3u0nl4f8wwv5eud4um904t6sjqrzuy2k2va3avhfvks9x8u2y
  hosts:
    - &THEBATTLESHIP age16nmkvhtvgnka8c50slt98qgcc3nyeztfym6aujgpny6z8d24sp7qldpyzc

# Creation rules for different secret files
creation_rules:
  # Shared secrets accessible by all users and hosts
  - path_regex: shared\.yaml$
    key_groups:
      - age:
          - *cody
          - *THEBATTLESHIP
  
  # Host-specific secrets for THEBATTLESHIP
  - path_regex: THEBATTLESHIP\.yaml$
    key_groups:
      - age:
          - *THEBATTLESHIP
          - *cody
